In [5]:
import numpy as np
import time

In [13]:
def add_matrix(A, B):
    """Add two matrices A and B."""
    return np.add(A, B)

def subtract_matrix(A, B):
    """Subtract matrix B from matrix A."""
    return np.subtract(A, B)

def strassen_multiply(A, B):
    """Multiply two matrices A and B using Strassen's algorithm."""
    if len(A) == 1:
        return A * B
    else:
        mid = len(A) // 2
        A11 = A[:mid, :mid]
        A12 = A[:mid, mid:]
        A21 = A[mid:, :mid]
        A22 = A[mid:, mid:]
        B11 = B[:mid, :mid]
        B12 = B[:mid, mid:]
        B21 = B[mid:, :mid]
        B22 = B[mid:, mid:]

        P1 = strassen_multiply(A11, B12 - B22)
        P2 = strassen_multiply(A11 + A12, B22)
        P3 = strassen_multiply(A21 + A22, B11)
        P4 = strassen_multiply(A22, B21 - B11)
        P5 = strassen_multiply(A11 + A22, B11 + B22)
        P6 = strassen_multiply(A12 - A22, B21 + B22)
        P7 = strassen_multiply(A11 - A21, B11 + B12)

        C11 = P5 + P4 - P2 + P6
        C12 = P1 + P2
        C21 = P3 + P4
        C22 = P5 + P1 - P3 - P7

        C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
        return C

def pad_matrix(A, size):
    """Pad matrix A to the specified size."""
    padded = np.zeros((size, size), dtype=A.dtype)
    padded[:A.shape[0], :A.shape[1]] = A
    return padded

In [14]:
# Generate two random 100x100 matrices and pad them to 128x128
size_original = 100
size_padded = 128
A = np.random.randint(1, 10, size=(size_original, size_original))
B = np.random.randint(1, 10, size=(size_original, size_original))
A_padded = pad_matrix(A, size_padded)
B_padded = pad_matrix(B, size_padded)

# Time the Strassen's multiplication for the padded matrices
start_time = time.time()
C_padded = strassen_multiply(A_padded, B_padded)
end_time = time.time()

# Extract the original sized product matrix
C = C_padded[:size_original, :size_original]

print("Time taken for multiplication: {:.6f} seconds".format(end_time - start_time))
print("\nProduct matrix (portion corresponding to the original 100x100 size):")
print(C)

Time taken for multiplication: 5.623995 seconds

Product matrix (portion corresponding to the original 100x100 size):
[[2454 2403 2484 ... 2486 2541 2545]
 [2271 2325 2454 ... 2396 2253 2552]
 [2510 2486 2647 ... 2434 2509 2748]
 ...
 [2494 2419 2774 ... 2646 2495 2663]
 [2455 2447 2593 ... 2565 2515 2600]
 [2540 2460 2600 ... 2532 2545 2634]]


In [10]:
import time
import random  # Required to use random.randint

# Generate 100x100 matrices
A = [[random.randint(0, 100) for _ in range(1000)] for _ in range(1000)]
B = [[random.randint(0, 100) for _ in range(1000)] for _ in range(1000)]

In [11]:
# Function to calculate matrix multiplication
def matrix_multiply(A, B):
    # Create a new matrix C with the same dimensions as the result of A * B
    C = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    
    for i in range(len(A)):
        for j in range(len(B[0])):
            sum = 0
            for k in range(len(B)):
                # Based on the conditions, decide whether to multiply and add, or just add
                if (i < j and j < k) or (i > j and j > k):
                    sum += A[i][k] * B[k][j]
                else:
                    sum += A[i][k] * B[k][j]
            # Set the C[i][j] element to the sum
            C[i][j] = sum
    
    return C

# Start the timer
start_time = time.time()

# Call the matrix multiplication function
result = matrix_multiply(A, B)

# Stop the timer and print the elapsed time
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")


Time taken: 290.0673818588257 seconds


In [12]:
# Strassen's Algorithm
import time
import random
import numpy as np  # Necessary for matrix operations

def add_matrix(A, B):
    """Add two matrices A and B."""
    return np.add(A, B)

def subtract_matrix(A, B):
    """Subtract matrix B from matrix A."""
    return np.subtract(A, B)

def strassen_multiply(A, B):
    """Multiply two matrices A and B using Strassen's algorithm."""
    if len(A) == 1:
        return A * B
    else:
        mid = len(A) // 2
        A11 = A[:mid, :mid]
        A12 = A[:mid, mid:]
        A21 = A[mid:, :mid]
        A22 = A[mid:, mid:]
        B11 = B[:mid, :mid]
        B12 = B[:mid, mid:]
        B21 = B[mid:, :mid]
        B22 = B[mid:, mid:]

        P1 = strassen_multiply(A11, subtract_matrix(B12, B22))
        P2 = strassen_multiply(add_matrix(A11, A12), B22)
        P3 = strassen_multiply(add_matrix(A21, A22), B11)
        P4 = strassen_multiply(A22, subtract_matrix(B21, B11))
        P5 = strassen_multiply(add_matrix(A11, A22), add_matrix(B11, B22))
        P6 = strassen_multiply(subtract_matrix(A12, A22), add_matrix(B21, B22))
        P7 = strassen_multiply(subtract_matrix(A11, A21), add_matrix(B11, B12))

        C11 = add_matrix(subtract_matrix(add_matrix(P5, P4), P2), P6)
        C12 = add_matrix(P1, P2)
        C21 = add_matrix(P3, P4)
        C22 = subtract_matrix(subtract_matrix(add_matrix(P5, P1), P3), P7)

        C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
        return C

def pad_matrix(A, size):
    """Pad matrix A to the specified size."""
    padded = np.zeros((size, size), dtype=A.dtype)
    padded[:A.shape[0], :A.shape[1]] = A
    return padded

# Generate and pad matrices outside the timing block
size_original = 100
size_padded = 128
A = np.random.randint(0, 101, size=(size_original, size_original))
B = np.random.randint(0, 101, size=(size_original, size_original))
A_padded = pad_matrix(A, size_padded)
B_padded = pad_matrix(B, size_padded)

# Time only the Strassen's multiplication
start_time = time.time()
C_padded = strassen_multiply(A_padded, B_padded)
end_time = time.time()

# Extract the original sized product matrix
C = C_padded[:size_original, :size_original]

# Display results
print("Time taken for multiplication: {:.6f} seconds".format(end_time - start_time))
print("\nProduct matrix (portion corresponding to the original 100x100 size):")
print(C)


Time taken for multiplication: 6.736013 seconds

Product matrix (portion corresponding to the original 100x100 size):
[[233698 266188 261200 ... 243405 270449 235983]
 [244705 265080 243552 ... 243827 261603 234761]
 [215299 233594 254392 ... 212941 239016 183157]
 ...
 [273406 286882 286245 ... 260915 270142 263726]
 [232977 265435 277903 ... 244304 260193 217001]
 [210306 240821 250104 ... 235486 268815 232528]]
